#!/bin/sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

destination=$1

POSTMARK_SERVER_TOKEN=$(cat | jq -r '.source.server_token')
export POSTMARK_SERVER_TOKEN

if [ -z "$destination" ]; then
  echo "usage: $0 <path/to/destination>" >&2
  exit 1
fi

postmark templates push -f "$1"

echo "{ \"version\": \"latest\", \"metadata\": [{ \"timestamp\": \"$(date)\" }] }" >&3

